services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: acaclick_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: acaclick_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # ðŸ‘‡ Muy importante:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  db_usuarios:
    image: postgres:16
    container_name: acaclick_db_usuarios
    restart: unless-stopped
    environment:
      POSTGRES_DB: acaclick_usuarios
      POSTGRES_USER: acaclick_user
      POSTGRES_PASSWORD: acaclick_password
    ports:
      - "5433:5432"
    volumes:
      - db_usuarios_data:/var/lib/postgresql/data

volumes:
  db_usuarios_data:
